"""Friday Movie Club API client."""

from .client import FMCClient
from .exceptions import (
    APIError,
    AuthenticationError,
    ConflictError,
    FMCError,
    ForbiddenError,
    NotFoundError,
    ValidationError,
)
from .models import (
    AggregateRanking,
    AuthResponse,
    Club,
    ClubStatus,
    EmailInvitation,
    Event,
    EventRSVP,
    EventStatus,
    Genre,
    InvitationStatus,
    Movie,
    MovieSuggestion,
    PaginatedResult,
    RSVPStatus,
    Schedule,
    ScheduleStatus,
    SuggestionStatus,
    TMDBSearchResponse,
    TMDBSearchResult,
    TokenPair,
    User,
    UserRole,
    UserToken,
)

__all__ = [
    # Client
    "FMCClient",
    # Exceptions
    "FMCError",
    "APIError",
    "AuthenticationError",
    "ForbiddenError",
    "NotFoundError",
    "ConflictError",
    "ValidationError",
    # Models
    "AggregateRanking",
    "AuthResponse",
    "Club",
    "ClubStatus",
    "EmailInvitation",
    "Event",
    "EventRSVP",
    "EventStatus",
    "Genre",
    "InvitationStatus",
    "Movie",
    "MovieSuggestion",
    "PaginatedResult",
    "RSVPStatus",
    "Schedule",
    "ScheduleStatus",
    "SocialLoginURL",
    "SuggestionStatus",
    "TMDBSearchResponse",
    "TMDBSearchResult",
    "TokenPair",
    "User",
    "UserRole",
    "UserToken",
]
